USE [master]
GO

/****** Object:  Database [DataExtractor]    Script Date: 7/19/2018 12:04:45 PM ******/
CREATE DATABASE [DataExtractor]
 CONTAINMENT = NONE
GO

ALTER DATABASE [DataExtractor] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataExtractor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataExtractor] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataExtractor] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataExtractor] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataExtractor] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataExtractor] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataExtractor] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DataExtractor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataExtractor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataExtractor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataExtractor] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataExtractor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataExtractor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataExtractor] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataExtractor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataExtractor] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataExtractor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataExtractor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataExtractor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataExtractor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataExtractor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataExtractor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataExtractor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataExtractor] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DataExtractor] SET  MULTI_USER 
GO

ALTER DATABASE [DataExtractor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataExtractor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataExtractor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataExtractor] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DataExtractor] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataExtractor] SET  READ_WRITE 
GO


